apiVersion: apps/v1
kind: Deployment
metadata:
  name: gblog
  labels:
    app: gblog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gblog
  template:
    metadata:
      labels:
        app: gblog
    spec:
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
      containers:
        - name: gblog
          image: gblog:latest
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 30
            timeoutSeconds: 3
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            runAsNonRoot: true

---
apiVersion: v1
kind: Service
metadata:
  name: gblog
  labels:
    app: gblog
spec:
  type: ClusterIP
  selector:
    app: gblog
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gblog
  labels:
    app: gblog
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: gerardosalazar.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gblog
                port:
                  number: 80
  tls:
    - hosts:
        - gerardosalazar.com
      secretName: gblog-tls

